---
driver:
  name: vagrant
  network:
    # The source / destination port need to be the same to properly test redirects and such.
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  customize:
    memory: 2048
    cpus: 1

provisioner:
  product_name: chef
  product_version: "<%= ENV.has_key?('CHEF_VERSION') ? ENV['CHEF_VERSION'] : 15 %>"
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  chef_license: accept
  # log_level: info

platforms:
  - name: oracle-8.2

suites:
  - name: default
    run_list:
      - 'recipe[cobblerd::default]'
  - name: images
    run_list:
      - 'recipe[cobblerd::centos]'
      # - 'recipe[cobblerd::ubuntu]'
  - name: web
    run_list:
      - 'recipe[cobblerd::web]'
  - name: create-distro
    run_list:
      - 'recipe[cobblerd::default]'
      - 'recipe[cobblerd_test::create_objects]'
      - 'recipe[cobblerd_test::delete_objects]'
    attributes:
      cobblerd:
        iso_test_hostname: <%= ENV.has_key?('COBBLER_ISO_SOURCE') ? ENV['COBBLER_ISO_SOURCE'] : '' %>
