AllCops:
  Exclude:
    - 'Vagrantfile'
  DisplayCopNames: true

Layout/AlignParameters:
  Enabled: false

Style/Encoding:
  Enabled: false

# TODO: Enable this in the future.
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 180

Style/StringLiterals:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'metadata.rb'

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 35
